name: hsf-india
channels:
  - defaults
  - nvidia/label/cuda-12.4.0
dependencies:
  - cuda-nvcc
  - libcurand
  - libcurand-dev
      
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/'"
# not needed for Delhi setup
#  NUMBA_CUDA_ENABLE_MINOR_VERSION_COMPATIBILITY: "1"
  
